### ISSUE TITLE
Not able to install 

### ISSUE THREAD

**Issue by avrajit** [DEIB-GECO/PyGMQL#32]
I am using ubuntu 16.04 system
Java version openjdk version "1.8.0_292"
`echo $JAVA_HOME ` 

`/usr/bin/java`
I created a separate conda environment with python 3.6 and and installed Jupyter note book
Then by using Jupyter note book I did
`!pip install gmql` 

it get installed successfully

now when I am trying to import 

`import gmql as gl`

it is showing this error  
`File "<string>", line unknown
ParseError: mismatched tag: line 13, column 4`

what mistake I am doing. I am bit new in python, please help

**Comment by lucananni93** [comment]
The issue should be solved now. Thanks for your patience!
